### ISSUE TITLE
Using CUDA 8?

### ISSUE THREAD

**Issue by jakirkham** [jjhelmus/docker-images#1]
So there is a CUDA 8 CentOS 6-based Docker image. Any thoughts on using that?

ref: https://gitlab.com/nvidia/cuda/blob/centos6/8.0/devel/cudnn5/Dockerfile

**Comment by jjhelmus** [comment]
A CUDA 8 docker image could be created but I have no reason for needing one at this time.  When I have the need I will be making one.

I should clarify that these docker images are for my own personal needs, I am not maintaining them for the community.  I'm happy for the community to benefit and use these images but am not soliciting updates from the community and will not be merging any changes if they do not meet my own personal package building needs.  I'll add a `README` to this repo indicating this shortly.
